let name = "название:Генератор защитного поля";
let price = "цена: 1000";
console.log(name);
console.log(price);
console.log('Выбран "Генератор защитного поля", цена за штуку 1000 кредитов');
console.log('Выбран "Генератор защитного поля", цена за штуку 2000 кредитов');
let nameNext = ` "Генератор защитного поля",`;
let priceNext = `цена за штуку 1000 кредитов`;
let priceNextTwo = `цена за штуку 2000 кредитов`;
let message = `Выбран ${nameNext} ${priceNext}`;
let messageTwo = `Выбран ${nameNext} ${priceNextTwo}`;
console.log(message);
console.log(messageTwo);
